package org.javamaster.httpclient.impl.ui;

import com.google.common.collect.Lists;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import consulo.fileChooser.FileChooserDescriptor;
import consulo.fileChooser.FileChooserDescriptorFactory;
import consulo.httpClient.localize.HttpClientLocalize;
import consulo.project.Project;
import consulo.ui.ex.awt.CollectionComboBoxModel;
import consulo.ui.ex.awt.TextBrowseFolderListener;
import consulo.ui.ex.awt.TextFieldWithBrowseButton;
import consulo.util.lang.Pair;
import org.javamaster.httpclient.HttpFileType;
import org.javamaster.httpclient.env.EnvFileService;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.List;
import java.util.Set;

public class ConfigSettingsForm {
    private JPanel mainPanel;

    private JComboBox<String> envComboBox;
    private TextFieldWithBrowseButton httpFileBtn;

    private final String noEnv = HttpClientLocalize.noEnv().get();

    public ConfigSettingsForm() {
        init();
    }

    public void initForm(String env, String httpFilePath, @NotNull Project project) {
        File httpFile = new File(httpFilePath);

        initEnvComboBox(env, httpFile, project);

        initFileBtn(httpFilePath);
    }

    public Pair<String, String> getPair() {
        String env = envComboBox.getSelectedItem() + "";
        if (env.equals(noEnv)) {
            env = "";
        }

        String fileName = httpFileBtn.getText();

        return new Pair<>(env, fileName);
    }

    private void initEnvComboBox(String env, File httpFile, Project project) {
        EnvFileService envFileService = EnvFileService.getService(project);

        File parentFile = httpFile.getParentFile();
        Set<String> presetEnvSet = envFileService.getPresetEnvSet(parentFile == null ? null : parentFile.getAbsolutePath());

        List<String> envNameList = Lists.newArrayList(noEnv);
        envNameList.addAll(presetEnvSet);

        envComboBox.setModel(new CollectionComboBoxModel<>(envNameList));

        envComboBox.setSelectedItem(env);
    }

    private void initFileBtn(String httpFilePath) {
        httpFileBtn.setText(httpFilePath);

        FileChooserDescriptor descriptor = FileChooserDescriptorFactory.createSingleFileDescriptor(HttpFileType.INSTANCE);

        httpFileBtn.addBrowseFolderListener(new TextBrowseFolderListener(descriptor) {

            @Override
            public void actionPerformed(ActionEvent e) {
                super.actionPerformed(e);

                httpFileBtn.setText(httpFileBtn.getText().replaceAll("\\\\", "/"));
            }

        });
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }


    /**
     * Method generated by Consulo GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void init() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        this.$$$loadLabelText$$$(label1, HttpClientLocalize.env().get());
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        envComboBox = new JComboBox();
        mainPanel.add(envComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        this.$$$loadLabelText$$$(label2, HttpClientLocalize.httpFile().get());
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        httpFileBtn = new TextFieldWithBrowseButton();
        mainPanel.add(httpFileBtn, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) {
                    break;
                }
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
